name: bookhive
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  firebase_core: ^2.14.0
  flutter_slidable: ^3.0.0
  image_picker: ^0.8.9
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  shared_preferences: ^2.1.2
  uuid: ^3.0.7
  cached_network_image: ^3.2.3
  liquid_pull_to_refresh: ^3.0.1
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
