// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyKmGEe1QFPfO-pVGvGwc1kXqW_UCh5bI',
    appId: '1:188374312413:web:a8fa395b18f5535413c234',
    messagingSenderId: '188374312413',
    projectId: 'bookhive-ccb69',
    authDomain: 'bookhive-ccb69.firebaseapp.com',
    storageBucket: 'bookhive-ccb69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCazmNNp3ZWVjti1Z3m2x8SbRaxCOQltVw',
    appId: '1:188374312413:android:8a12ee6e5bcf6ab413c234',
    messagingSenderId: '188374312413',
    projectId: 'bookhive-ccb69',
    storageBucket: 'bookhive-ccb69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRyw0Ip2HC9vYXefwNyPsHgLeei8P-vLc',
    appId: '1:188374312413:ios:fb8d550fae1f0d4013c234',
    messagingSenderId: '188374312413',
    projectId: 'bookhive-ccb69',
    storageBucket: 'bookhive-ccb69.appspot.com',
    iosClientId: '188374312413-dubjhmqlk0sq72dshr8lm7cfc7trseqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookhive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRyw0Ip2HC9vYXefwNyPsHgLeei8P-vLc',
    appId: '1:188374312413:ios:da48118caa126b4813c234',
    messagingSenderId: '188374312413',
    projectId: 'bookhive-ccb69',
    storageBucket: 'bookhive-ccb69.appspot.com',
    iosClientId: '188374312413-4g3f0sifloj6m257dsbhccsg6hmmbktt.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookhive.RunnerTests',
  );
}
